// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvqRPcrQ3FYa0MxyxkfFhx_ZIeACsg-as',
    appId: '1:820620575208:web:055c117a1ff816cc0ca45d',
    messagingSenderId: '820620575208',
    projectId: 'intelligent-course-allocation',
    authDomain: 'intelligent-course-allocation.firebaseapp.com',
    storageBucket: 'intelligent-course-allocation.appspot.com',
    measurementId: 'G-VYR78Q582Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI9-ziqwf3NGSzqkO539scoifYBln0Sd4',
    appId: '1:820620575208:android:89de3d9331ebef9d0ca45d',
    messagingSenderId: '820620575208',
    projectId: 'intelligent-course-allocation',
    storageBucket: 'intelligent-course-allocation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEwcOS3sDApVOTcrnz23MhprwdQxtfMP8',
    appId: '1:820620575208:ios:1a08cbfcb2bf160d0ca45d',
    messagingSenderId: '820620575208',
    projectId: 'intelligent-course-allocation',
    storageBucket: 'intelligent-course-allocation.appspot.com',
    androidClientId: '820620575208-e2kn2f9gp2u6p4ses46s6uv6l2e0la6p.apps.googleusercontent.com',
    iosClientId: '820620575208-1f346985etg41nkpji4c504t95kkjodg.apps.googleusercontent.com',
    iosBundleId: 'com.example.intelligentCourseAllocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEwcOS3sDApVOTcrnz23MhprwdQxtfMP8',
    appId: '1:820620575208:ios:1a08cbfcb2bf160d0ca45d',
    messagingSenderId: '820620575208',
    projectId: 'intelligent-course-allocation',
    storageBucket: 'intelligent-course-allocation.appspot.com',
    androidClientId: '820620575208-e2kn2f9gp2u6p4ses46s6uv6l2e0la6p.apps.googleusercontent.com',
    iosClientId: '820620575208-1f346985etg41nkpji4c504t95kkjodg.apps.googleusercontent.com',
    iosBundleId: 'com.example.intelligentCourseAllocation',
  );
}
